default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: burn_development

test:
  <<: *default
  database: burn_test

production:
  <<: *default
  host: <%= ENV['database_host'] %>
  database: <%= ENV['database_db'] %>
  username: <%= ENV['database_user'] %>
  password: <%= ENV['database_pass'] %>
